export const ACTION_REQUEST = "ACTION_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT = "LOGOUT";

export const GET_POST_REQUEST = "GET_POST_REQUEST"
export const GET_POST_SUCCESS = "GET_POST_SUCCESS"
export const GET_POST_FAILURE = "GET_POST_FAILURE"
export const STOP_GET_POST = "STOP_ GET_POST"

export const GET_COMMENT_REQUEST = "GET_COMMENT_REQUEST"
export const GET_COMMENT_SUCCESS = "GET_COMMENT_SUCCESS"
export const GET_COMMENT_FAILURE = "GET_COMMENT_FAILURE"

export const GET_ADMIN_POST_REQUEST = "GET_ADMIN_POST_REQUEST"
export const GET_ADMIN_POST_SUCCESS = "GET_ADMIN_POST_SUCCESS"
export const GET_ADMIN_POST_FAILURE = "GET_ADMIN_POST_FAILURE"
